export const SET_LOADER_STATE = 'SET_LOADER_STATE';
export const SET_GENOME_DATA = 'SET_GENOME_DATA';
export const SET_SOURCE_LINE = 'SET_SOURCE_LINE';
export const SET_TARGET_LINES = 'SET_TARGET_LINES';